Test: &TEST
  description: Contains all of the fields needed to collate and run a test
  fields:
  - name: resources
    type: str | list
    description: Path to a directory containing resources to use for tests
    default: ''
  - name: exclude_resources
    type: str | list | None
    description: Resources to exclude from testing and coverage
    default: null
  - name: exclude_functions
    type: str | list | None
    description: Functions to exclude from testing and coverage
    default: null
  - name: module
    type: Any
    description: A module or the location to a module in the file system
    default: null
  - name: module_location
    type: str
    description: Location of a module in the file system
    default: null
  - name: function
    type: str
    description: Name of the function to test
    default: ''
  - name: function_name
    type: str
    description: Name of the function to test
    default: ''
  - name: cast_arguments
    description: Cast whole or parts of a function's arguments
    type: List[dict | Cast] | None
    default: null
  - name: cast_output
    description: Cast whole or parts of a function's result
    type: List[dict | Cast] | None
    default: null
  - name: description
    type: str
    description: Description for a module, test, or case
    default: ''
  - name: patches
    type: List[dict] | None
    description: List containing info on objects to patch
    default: null
  - name: environment
    type: dict
    default: {}
    description: Environment variables to use for tests
  - name: arguments
    type: dict
    default: {}
    description: Keyword arguments to pass to functions
  - name: assertions
    type: List[dict]
    default: []
    description: >
      A list of assertions and expected results to verify against
      the actual result
  - name: yaml
    type: str
    description: Path to a YAML test file
  - name: output
    type: Any
    default: null
    description: Store results of running the function
  - name: id
    type: str
    default: null
    description: Unique long ID assigned to each tests
  - name: id_long
    type: str
    default: ''
    description: Unique short ID assigned to each tests
  - name: id_short
    type: str
    default: ''
    description: Unique ID assigned to each tests
  - name: module_route
    type: str
    description: Location of a module in the file system
    default: ''
  - name: tests
    type: list
    description: Store collated, individual tests
    default: null
  - name: key
    type: str
    description: ey or unique identifier for a test
    default: null


# Update names
main.app.Data: &MAIN_DATA
  description: Store data used by the functions in a module
  fields:
  - name: project_path
    type: str
    description: >
      The directory containing files to test or path to a module or
      YAML file to test
  - name: exclude_files
    type: str | list
    description: Patterns to match to files for excluding files from testing
    default: null
  - name: include_files
    type: str | list
    description: Patterns to match to files for including files from testing
    default: null
  - name: exclude_functions
    type: str | list
    description: Functions to exclude from testing
    default: null
  - name: include_functions
    type: str | list
    description: Functions to filter or include for testing
    default: null
  - name: yaml_suffix
    type: str
    description: Suffix for YAML files containing tests
    default: null
  - name: timestamp
    type: str | list
    description: Seconds since epoch
    default: null
  - name: locations
    type: dict
    description: The locations of modules, YAML files, and resources
    default: null
  - name: resources
    type: list
    description: >
      A list of resource module locations. The modules are used for all tests
    default: []
  - name: logging_enabled
    type: bool
    description: Flag to enable or disable logging
    default: False

Patch: &PATCH
  description: Data needed to perform a patch operation
  fields:
  - name: name
    description: Dot-delimited name of the object to patch
    type: str
  - name: route
    description: Dot-delimited route of the object to be patched
    type: str
    default: null
  - name: callable_route
    description: Dot-delimited route to a callable within the module to test
    type: str
    default: null
  - name: method
    description: Method for how to patch the object
    type: str
    default: null
  - name: value
    description: Value used to patch an object
    type: Any
    default: null
  - name: timestamp
    description: A timestamp of key used to access patches
    type: int
    default: 0
  - name: patch
    description: The object used as a patch
    type: Any
    default: null
  - name: module
    description: Module containing the object to patch
    type:  ModuleType
    default: null
  - name: do_nothing
    description: Flag to do nothing if patch method is not found
    type:  bool
    default: False
Patch_Data: &PATCH_DATA
  description: Store data used by the functions in a module
  fields:
  - name: module
    description: Module containing the object to patch
    type:  ModuleType
    default: null
  - name: patches
    description: A list of patches to process
    type: object
    default: []
  - name: i
    description: The ith iteration through a list of patches
    type: int
    default: 0
  - name: patch
    description: A Patch object
    type: Patch
    default: null
Patch_Side_Effect_List: &PATCH_SIDE_EFFECT_LIST
  description: DataClass needed to create a list side effect
  fields:
  - name: value
    description: List of values for the side effect
    type: List[Any]
    default: []
  - name: count
    type: int
    default: 0
    description: Track the number of times the side effect has been called
Patch_Parents: &PATCH_PARENTS
  description: Store the names, values, and types of an objects parents
  fields:
  - name: names
    description: The name of each parent
    type:  List[str]
    default: ''
  - name: values
    description: The value of each parent
    type: List[Any]
    default: []
  - name: types
    description: The type of each parent
    type: List[str]
    default: []
Cast_Kinds: &CAST_KINDS
  description: Store the kinds of casters, objects, and casted_objects
  fields:
  - name: caster
    type: str | Any
    description: The type of the object
    default: null
  - name: object
    type: str
    description: Any object
    default: null
  - name: casted_object
    type: str
    description: The type of the object
    default: null
Cast: &CAST
  description: Store data needed to cast an object
  fields:
  - name: method
    type: str
    description: Dot-delimited path to the casting method
    default: null
  - name: unpack
    type: bool
    description: Cast an packed or unpacked object
    default: true
  - name: module
    type: ModuleType
    description: Module containing the cast object
    default: null
  - name: object
    type: Any
    description: Any object
    default: null
  - name: casted_object
    type: str
    description: The result from casting an object
    default: null
  - name: field
    type: str
    description: The name of a field or attribute of an object
    default: ''
  - name: unpack
    type: bool
    description: Cast an packed or unpacked object
    default: false
  - name: module
    type: ModuleType
    description: Module containing the cast object
    default: null


process_casts.Data: &CAST_DATA
  description: Store data used by the functions in a module
  fields:
  - name: object
    type: Any
    description: Any object
    default: null
  - name: kinds
    type: DataClass
    description: Stores the kind of objects
    default: null
  - name: object_key
    type: str
    description: Key for the field (arguments, output, or object) to cast
    default: ''
  - name: casts
    type: List[dict]
    description: List of individual casts to perform
    default: []
  - name: cast
    type: dict
    description: List of individual casts to perform
    default: {}
  - name: i
    type: int
    description: Index for an element in a list
    default: 0
  - name: module
    type: ModuleType
    description: Module containing the caster
    default: null


process_assertions.Assertion: &PROCESS_ASSERTIONS_ASSERTION
  description: Store data needed to process an assertion form a test
  fields:
  - name: id
    description: >
      A unique ID for each test consisting of the route to the function, the
      tests unique key or number, and a description of the test
    type: str
    default: ''
  - name: id_short
    description: The route to the function
    type: str
    default: ''
  - name: module
    type: ModuleType | str
    description: > 
      The module containing the function to test or the module's location
    default: null
  - name: method
    type: str
    description: The assertion method
  - name: field
    type: str
    description: Dot-delimited path to an attribute or key of the result
  - name: expected
    type: Any
    description: Expected value
  - name: output
    type: Any
    description: Output from the function to verify
  - name: cast_output
    type: list
    description: Casts to perform on the output before verifying expected output
  - name: passed
    type: bool
    default: false
    description: Flag indicating whether a test was passed or not
process_assertions.Data: &PROCESS_ASSERTIONS_ASSERTION_DATA
  description: Store data used by the functions within the module
  fields:
  - name: module
    type: Any
    description: Module containing the verification or assertion functions
    default: null
  - name: assertions
    type: list
    description: List of dictionaries or assertion objects
    default: []
  - name: output
    type: Any
    description: Output from calling a function
    default: []
  - name: i
    type: int
    description: Value of the current iteration in a loop
    default: 0
  - name: assertion
    type: dict
    description: The ith assertion from a list of assertions
    default: {}
  - name: id
    type: str
    description: A longer unique identifier for a test
    default: ''
  - name: id_short
    type: str
    description: A shorter unique identifier for a test
    default: ''
get_object.Parents: &GET_OBJECT_PARENTS
  description: >
    Store the names, values, and types of the
    parents of an object
  fields:
  - name: names
    type: list
    description: The names of an object's parents
    default: null
  - name: values
    type: list
    description: The values of an object's parents
    default: null
  - name: types
    type: list
    description: The types of an object's parents
    default: null
get_object.Data: &GET_OBJECT_DATA
  description: Data used by the functions within the module
  fields:
  - name: parent
    type: sns
    description: An object's parent
    default: null
  - name: name
    type: str
    description: Name of an object's parent
    default: null
  - name: parents
    type: sns
    description: Store parent data for an object
    default: null
  - name: names
    type: list
    description: The names of an object's parents
    default: []
get_config.Data: &GET_CONFIG_DATA
  description: Store and process data from YAML files associated with modules
  fields:
  - name: module
    type: str
    description: The location of a module
    default: ''
  - name: yaml
    type: str
    description: The location of a YAML file
    default: ''
  - name: contents
    type: dict
    description: Content from a YAML file
    default: {}
  - name: config
    type: str | dict
    description: >
      The content from a YAML file formatted so that top level keys can be
      accessed using dot notation
    default: {}
  - name: environment
    type: str | dict
    default: {}
    description: Environment variables used by a module
  - name: schema
    type: str | dict
    default: {}
    description: Schema used by a module
  - name: nested
    type: List[str]
    default: []
    description: null
run_multiple_threads.Data: &RUN_MULTIPLES_THREADS_DATA
  description: Store data used by the functions in a module
  fields:
  - name: target
    type: Callable
    description: The target function to run in a threads
    default: null
  - name: args
    type: list | tuple
    description: Arguments passed to a function
    default: null
  - name: kwargs
    type: dict
    description: Keyword arguments passed to a function
    default: null
  - name: store_name
    type: str
    description: >
      The name of a global variable in a function's module,
      that's used to store results of functions run inside threads
    default: null
  - name: results
    type: list
    description: The results of running the functions
    default: null
  - name: timestamp
    type: int | list
    description: An integer timestamp
    default: null
  - name: arguments
    type: list
    description: Arguments passed to a function called within a thread
    default: null
  - name: threads
    type: list
    description: Store threads created for multi-threading
    default: null
  - name: result_key
    type: str
    description: >
      The dictionary key the results from running the threads is saved to
    default: ''
  - name: kind
    type: str
    description: The kind or type of an object
    default: ''
logger.Data: &LOGGER_DATA
  description: Data needed to call the the logger
  fields:
  - name: directory
    type: str
    description: Directory to store logs in
    default: null
  - name: data
    type: Any
    description: Data to log
    default: null
  - name: format
    type: str
    description: Format for the log - `json` or `yaml`
    default: yaml
  - name: standard_output
    type: bool
    description: Flag for outputting to terminal
    default: false
  - name: location
    type: str
    description: Location of a log file
    default: ''
  - name: timestamp
    type: int
    description: Timestamp, seconds past epoch
    default: null
  - name: level
    type: str
    description: Logging level
    default: debug
  - name: status
    type: str
    description: Status of logging data - success or fail
    default: success
  - name: enabled
    type: bool
    description: Enable or disable logging
    default: true


