environment:
  PYTEST_YAML_ROOT_DIR: ${PYTEST_YAML_ROOT_DIR}


# schema:
# - cls_name: Data
#   description: Data processed by functions within the module
#   slots: False
#   fields:
#   - name: pytest_config
#     type: py_test.Config | None
#   - name: pytest_parser
#     type: py_test.Parser | None
#   - name: pytest_instance
#     type: ModuleType | None
#   - name: project_directory
#     type: str | None


options:
- args: resources
  options:
    action: store
    help: Path to a directory python file that contains resources for the test
    required: false
    dest: resources
    default: []
- args: project-directory
  options:
    action: store
    help: Directory containing python files to test.
    required: false
    dest: project_directory
    default: .
- args: include-functions
  options:
    action: store
    help: A list of functions to include for testing
    required: false
    dest: include_functions
    default: []
- args: exclude-files
  options:
    action: store
    help: >
      A list of patterns for excluding files represented as a comma
      delimited string
    default:
    - .venv
    - .eggs
    - build
    - __pycache__
    nargs: +
    # - ignore
    # - _resources
    dest: exclude_files
    required: false
    # type: str
  help: A list of strings. Exclude python files containing on of the strings
- args: resources-folder-name
  options:
    action: store
    help: The names of folders containing resources for tests.
    default: _resources
    dest: resources_folder_name
    required: false
  help: A string. The names of folders containing resources for tests.
- args: yaml-suffix
  options:
    action: store
    help: >
      he suffix at the end of YAML filename that's used to identify test files
    default: _test
    dest: yaml_suffix
    required: false
  help: >
    A string. The suffix at the end of YAML filename that's used to identify
    test files
- args: logging-enabled
  options:
    action: store
    help: >
      Disables all
    default: true
    dest: logging_enabled
    required: false
  help: >
    A boolean. The suffix at the end of YAML filename that's used to identify
    test files


root_paths:
- .
- ''
- null
- None


null_types:
- nonetype
- notsettype
