environment:
  DEBUG: ${YAML_TESTING_FRAMEWORK_DEBUG}


unpack_kinds:
- list
- tuple
- dict
- module
- dataclass
- nonetype


object_kinds:
- list
- dict
- module
- dataclass
- nonetype


casted_object_kinds:
- list
- dict
- module
- dataclass
- nonetype


caster_kinds:
- dataclass
- function
- callable
- type
- nonetype


empty_values:
- null
- None
- []
- '[]'
- {}
- '{}'
- ''
- False
- 'False'
- 'false'
- 0
- '0'


operations:
  main:
  - process_casts
  process_casts:
  - get_cast_method
  - get_temp_object
  - handle_casting.main
  - reset_object


schema:
  Main:
    description: Store data needed to cast an object
    fields:
    - &MODULE
      name: module
      type: ModuleType
      description: Module containing the cast object
      default: null
    - name: casts
      type: list
      description: A list of `cast` object to process
      default: null
    - &OBJECT
      name: object
      type: Any
      description: Any object
      default: null
  Cast:
    description: Store data needed to cast an object
    fields:
    - *MODULE
    - *OBJECT
    - name: method
      type: str
      description: Dot-delimited path to the casting method
      default: null
    - name: unpack
      type: bool
      description: Cast an packed or unpacked object
      default: false
    - name: temp_object
      type: str
      description: The result from casting an object
      default: null
    - name: field
      type: str
      description: The name of a field or attribute of an object
      default: ''
    - name: result
      type: Any
      description: The result from casting an object
      default: null