environment:
  ROOT_DIR: ${YAML_TESTING_FRAMEWORK_ROOT_DIR}
  DEBUG: ${YAML_TESTING_FRAMEWORK_DEBUG}


empty_values:
- ''
- None
- '[]'
- '{}'
- null
- []
- {}


# schema:
# - &DATA
#   cls_name: Data
#   description: Store data used by the functions in a module
#   slots: False
#   fields:
#   - name: globals
#     type: dict | None
#     description: Store content from the sh`globals` key of a YAML file
#     default: {}
#   - name: tests
#     type: list | None
#     description: Store tests defined in YAML files
#     default: {}
#   - name: tree
#     type: Any | None
#     description: We use a tree to build out or collate individual tests
#     default: null
#   - name: parents
#     type: list | None
#     description: >
#       Store tests that are parents. These are tests that have nested tests
#     default: []
#   - name: roots
#     type: list | None
#     description: >
#       Store indices of the initial or original tests defined in YAML files
#     default: []
#   - name: visited
#     type: list | None
#     description: >
#       Keep track of root, parent, and child tests that have been visited
#     default: []
#   - name: branch_key
#     type: Any | None
#     description: Store the value of a branch key
#     default: ''
#   - name: branches_added
#     type: boolean | None
#     description: Flag if children branches are added to tree
#     default: False
#   - name: store
#     type: Any | None
#     description: Store the value of a branch key
#     default: null
#   - name: tmp
#     type: Any | None
#     description: Temp
#     default: null
#     # refactor
#   - name: module
#     type: str | None
#     description: The module to test
#     default: ''
#   - name: yaml
#     type: str | None
#     description: The YAML file containing tests for the module
#     default: ''
#   - name: module_route
#     type: str | None
#     description: The dot-delimited location of the module
#     default: ''
#   - name: resources
#     type: list | None
#     description: Resources to use when testing the module
#     default: []
#   - name: content
#     type: dict | None
#     description: The content of the YAML containing tests
#     default: {}
#   - name: test_kinds
#     type: list | None
#     description: Kinds of tests with in a YAML file or content
#     default: []
# - &TEST
#   cls_name: Test
#   description: Contains all of the fields needed to collate and run a test
#   slots: true
#   fields:
#   - name: resources
#     type: str | list | None
#     description: Path to a directory containing resources to use for tests
#     default: ''
#   - name: exclude
#     type: str | list | None
#     description: Functions to exclude from testing and coverage
#     default: []
#   - name: module
#     type: Any | None
#     description: A module or the location to a module in the file system
#     default: null
#   - name: function
#     type: str | None
#     description: Name of the function to test
#     default: ''
#   - name: function_name
#     type: str | None
#     description: Name of the function to test
#     default: ''
#   - name: cast_arguments
#     description: Cast whole or parts of a function's arguments
#     type: List[dict | Cast] | None
#     default: []
#   - name: cast_output
#     description: Cast whole or parts of a function's result
#     type: List[dict | Cast] | None
#     default: []
#   - name: description
#     type: str | None
#     description: Description for a module, test, or case
#     default: ''
#   - name: patches
#     type: list | None
#     description: List containing info on objects to patch
#     default: ''
#   - name: environment
#     type: dict | None
#     default: {}
#     description: Environment variables to use for tests
#   - name: arguments
#     type: dict | None
#     default: {}
#     description: Keyword arguments to pass to functions
#   - name: assertions
#     type: list | None
#     default: []
#     description: >
#       A list of assertions and expected results to verify against
#       the actual result
#   - name: yaml
#     type: str | None
#     description: Path to a YAML test file
#   - name: exception
#     type: dict | None
#     default: {}
#     description: Store any exceptions that occur when runninng a function
#   - name: result
#     type: Any | None
#     default: {}
#     description: Store results of running the function
#   - name: output
#     type: Any | None
#     default: null
#     description: Store results of running the function
#   - name: project_path
#     type: str | None
#     default: null
#     description: Location of the project's working directory
#   # Order matters
#   # IDs are formatted last
#   - name: id
#     type: str | None
#     default: null
#     description: Unique long ID assigned to each tests
#   - name: id_long
#     type: str | None
#     default: ''
#     description: Unique short ID assigned to each tests
#   - name: id_short
#     type: str | None
#     default: ''
#     description: Unique ID assigned to each tests
#   - name: cast_group
#     type: list | None
#     default: []
#     description: >
#       Keep track of which group, arguments of result,
#       to cast
#   - name: module_route
#     type: str | None
#     description: Location of a module in the file system
#     default: ''
#   - name: n
#     type: int | None
#     description: Store the length of an object
#     default: 0
#   - name: timestamp
#     type: int | None
#     description: A timestamp represented as a integer
#     default: null
#   - name: tests
#     type: list | None
#     description: Store collated, individual tests
#     default: null
#   - name: key
#     type: str | None
#     description: ey or unique identifier for a test
#     default: null


operations:
  main:
  - get_configurations_and_tests
  - format_locations
  - add_locations_to_configurations
  - get_expanded_nodes


content_keys_and_defaults:
  configurations: {}
  tests: []
