TODO:
- add logic to run tests for specified functions only


resources:
- https://stackoverflow.com/questions/5067604/determine-function-name-from-within-that-function-without-using-traceback


environment:
  ROOT_DIR: ${YAML_TESTING_FRAMEWORK_ROOT_DIR}
  DEBUG: ${YAML_TESTING_FRAMEWORK_DEBUG}


function_output_fields:
- result
- exception


cast_groups:
- arguments
- result


module_extensions:
- .py


order_of_operations:
  set_configs: null
  get_file_paths:
  - get python file paths
  - get associated yaml paths
  - get paths of test resources
  format_yaml_content: null


exclude_lines: []


exclude_files:
- .venv
- .eggs
- build
- __pycache__
- resource


locations:
- module
- yaml
- resources


empty_values:
- None
- null
- '[]'
- []
- ''
- '{}'
- {}


test_kinds:
- function


# Order of operations for testing functions
# and the fields/values of an object that are
# required to run functions
operations:
  run_test_for_functions:
  - handle_id
  - handle_module
  - handle_resources
  - process_environment
  - process_patches
  - process_cast_arguments
  - process_spies
  - get_function
  - get_function_output
  - process_cast_output
  - process_checks
  run_tests:
  - process_nodes
  - run_test_handler
  main:
  - process_locations
  - run_tests


unpack_kinds:
- iterable
- dict
- list
- tuple


schema:
  App:
    description: Store data used by the functions in a module
    fields:
    - name: project_path
      type: str
      description: >
        The directory containing files to test or path to a module or
        YAML file to test
    - name: exclude_files
      type: str | list
      description: Patterns to match to files for excluding files from testing
      default: null
    - name: include_files
      type: str | list
      description: Patterns to match to files for including files from testing
      default: null
    - name: exclude_functions
      type: str | list
      description: Functions to exclude from testing
      default: null
    - name: include_functions
      type: str | list
      description: Functions to filter or include for testing
      default: null
    - name: yaml_suffix
      type: str
      description: Suffix for YAML files containing tests
      default: null
    - name: timestamp
      type: str | list
      description: Seconds since epoch
      default: null
    - name: locations
      type: dict
      description: The locations of modules, YAML files, and resources
      default: null
    - name: resources
      type: list
      description: >
        A list of resource module locations. The modules are used for all tests
      default: []
    - name: logging_enabled
      type: bool
      description: Flag to enable or disable logging
      default: False
