Example_1:
  description: Example scheme
  fields:
  - name: string
    type: str
    description: String field
    default: ''
  - name: integer
    type: int
    description: Integer field
    default: 1
Example_2:
  description: Example scheme
  fields:
  - name: list
    type: list
    description: List field
    default: []
  - name: dictionary
    type: dict
    description: Dictionary field
    default: {}