environment:
  ROOT_DIR: ${YAML_TESTING_FRAMEWORK_ROOT_DIR}
  DEBUG: ${YAML_TESTING_FRAMEWORK_DEBUG}


operations:
  main:
  - pre_processing
  - get_patch_method
  - patch_module


empty_values:
- null
- None
- []
- '[]'
- '{}'
- {}
