environment:
  ROOT_DIR: ${ROOT_DIR}
  PYTEST_YAML_LOGS_DIR: ${ROOT_DIR}/.logs
  PYTEST_YAML_DEBUG: ${PYTEST_YAML_DEBUG}


schema:
- &DATA
  cls_name: Data
  description: Store data used by the functions in a module
  slots: true
  fields:
  - name: data
    description: Data_Class to log
    default: null
    type: Any | None
  - name: format_
    description: >
      Format for the log:  'json' or 'yaml'
    default: yaml
    type: str | None
  - name: standard_output
    description: Flag for outputting to terminal
    default: false
    type: bool
  - name: location
    description: Location of a log file
    default: debug
    type: str | None
  - name: timestamp
    description: Timestamp, seconds past epoch
    default: null
    type: int | None
  - name: level
    description: Logging level
    default: debug
    type: str | None
  - name: status
    type: str
    description: Status of a function's execution
    default: ''
  - name: enabled
    type: bool
    description: Enable or disable logging
    default: False
- &OPERATIONS
  cls_name: Operations
  description: Store data for performing operations on data
  slots: False
  fields:
  - name: parameters
    type: dict | None
    description: A function's parameters
    default: null
  - name: results
    type: dict | None
    description: The result of calling a function
    default: {}
  - name: fields
    type: dict | None
    description: Parameters/arguments to pass to functions
    default: {}
  - name: function
    type: Callable | None
    description: A function to call
    default: null


empty_values:
- false
- 'false'
- 'False'
- null
- None
- 0
- '0'
- ''


operations:
- format_location
- format_data
- convert_data
- format_level
- log_data
- output_to_terminal
