environment:
  ROOT_DIR: ${YAML_TESTING_FRAMEWORK_ROOT_DIR}
  DEBUG: ${YAML_TESTING_FRAMEWORK_DEBUG}


empty_values:
- ''
- None
- '[]'
- '{}'
- null
- []
- {}


operations:
  main:
  - get_configurations_and_tests
  - format_locations
  - add_locations_to_configurations
  - get_expanded_nodes


content_keys_and_defaults:
  configurations: {}
  tests: []
