Test: &TEST
  description: Contains all of the fields needed to collate and run a test
  fields:
  - name: resources
    type: str | list
    description: Path to a directory containing resources to use for tests
    default: ''
  - name: exclude_resources
    type: str | list | None
    description: Resources to exclude from testing and coverage
    default: null
  - name: exclude_functions
    type: str | list | None
    description: Functions to exclude from testing and coverage
    default: null
  - name: module
    type: Any
    description: A module or the location to a module in the file system
    default: null
  - name: function
    type: str
    description: Name of the function to test
    default: ''
  - name: function_name
    type: str
    description: Name of the function to test
    default: ''
  - name: cast_arguments
    description: Cast whole or parts of a function's arguments
    type: List[dict | Cast] | None
    default: null
  - name: cast_output
    description: Cast whole or parts of a function's result
    type: List[dict | Cast] | None
    default: null
  - name: description
    type: str
    description: Description for a module, test, or case
    default: ''
  - name: patches
    type: List[dict] | None
    description: List containing info on objects to patch
    default: null
  - name: environment
    type: dict
    default: {}
    description: Environment variables to use for tests
  - name: arguments
    type: dict
    default: {}
    description: Keyword arguments to pass to functions
  - name: checks
    type: List[dict]
    default: []
    description: >
      A list of checks and expected results to verify against
      the actual result
  - name: yaml
    type: str
    description: Path to a YAML test file
  - name: output
    type: Any
    default: null
    description: Store results of running the function
  - name: id
    type: str
    default: null
    description: Unique long ID assigned to each tests
  - name: id_long
    type: str
    default: ''
    description: Unique short ID assigned to each tests
  - name: id_short
    type: str
    default: ''
    description: Unique ID assigned to each tests
  - name: module_route
    type: str
    description: Location of a module in the file system
    default: ''
  - name: tests
    type: list
    description: Store collated, individual tests
    default: null
  - name: key
    type: str
    description: ey or unique identifier for a test
    default: null
  - name: spies
    type: list | str
    description: >
      A list of methods to spy, where each item in the list is the dot
      delimited route to a method
    default: null


Cast_Kinds: &CAST_KINDS
  description: Store the kinds of casters, objects, and casted_objects
  fields:
  - name: caster
    type: str | Any
    description: The type of the object
    default: null
  - name: object
    type: str
    description: Any object
    default: null
  - name: casted_object
    type: str
    description: The type of the object
    default: null
Cast: &CAST
  description: Store data needed to cast an object
  fields:
  - name: method
    type: str
    description: Dot-delimited path to the casting method
    default: null
  - name: unpack
    type: bool
    description: Cast an packed or unpacked object
    default: true
  - name: module
    type: ModuleType
    description: Module containing the cast object
    default: null
  - name: object
    type: Any
    description: Any object
    default: null
  - name: casted_object
    type: str
    description: The result from casting an object
    default: null
  - name: field
    type: str
    description: The name of a field or attribute of an object
    default: ''
  - name: unpack
    type: bool
    description: Cast an packed or unpacked object
    default: false
  - name: module
    type: ModuleType
    description: Module containing the cast object
    default: null


process_casts.Data: &CAST_DATA
  description: Store data used by the functions in a module
  fields:
  - name: object
    type: Any
    description: Any object
    default: null
  - name: kinds
    type: DataClass
    description: Stores the kind of objects
    default: null
  - name: object_key
    type: str
    description: Key for the field (arguments, output, or object) to cast
    default: ''
  - name: casts
    type: List[dict]
    description: List of individual casts to perform
    default: []
  - name: cast
    type: dict
    description: List of individual casts to perform
    default: {}
  - name: i
    type: int
    description: Index for an element in a list
    default: 0
  - name: module
    type: ModuleType
    description: Module containing the caster
    default: null


get_config.Data: &GET_CONFIG_DATA
  description: Store and process data from YAML files associated with modules
  fields:
  - name: module
    type: str
    description: The location of a module
    default: ''
  - name: yaml
    type: str
    description: The location of a YAML file
    default: ''
  - name: contents
    type: dict
    description: Content from a YAML file
    default: {}
  - name: config
    type: str | dict
    description: >
      The content from a YAML file formatted so that top level keys can be
      accessed using dot notation
    default: {}
  - name: environment
    type: str | dict
    default: {}
    description: Environment variables used by a module
  - name: schema
    type: str | dict
    default: {}
    description: Schema used by a module
  - name: nested
    type: List[str]
    default: []
    description: null
run_multiple_threads.Data: &RUN_MULTIPLES_THREADS_DATA
  description: Store data used by the functions in a module
  fields:
  - name: target
    type: Callable
    description: The target function to run in a threads
    default: null
  - name: args
    type: list | tuple
    description: Arguments passed to a function
    default: null
  - name: kwargs
    type: dict
    description: Keyword arguments passed to a function
    default: null
  - name: store_name
    type: str
    description: >
      The name of a global variable in a function's module,
      that's used to store results of functions run inside threads
    default: null
  - name: results
    type: list
    description: The results of running the functions
    default: null
  - name: timestamp
    type: int | list
    description: An integer timestamp
    default: null
  - name: arguments
    type: list
    description: Arguments passed to a function called within a thread
    default: null
  - name: threads
    type: list
    description: Store threads created for multi-threading
    default: null
  - name: result_key
    type: str
    description: >
      The dictionary key the results from running the threads is saved to
    default: ''
  - name: kind
    type: str
    description: The kind or type of an object
    default: ''
logger.Data: &LOGGER_DATA
  description: Data needed to call the the logger
  fields:
  - name: directory
    type: str
    description: Directory to store logs in
    default: null
  - name: data
    type: Any
    description: Data to log
    default: null
  - name: format
    type: str
    description: Format for the log - `json` or `yaml`
    default: yaml
  - name: standard_output
    type: bool
    description: Flag for outputting to terminal
    default: false
  - name: location
    type: str
    description: Location of a log file
    default: ''
  - name: timestamp
    type: int
    description: Timestamp, seconds past epoch
    default: null
  - name: level
    type: str
    description: Logging level
    default: debug
  - name: status
    type: str
    description: Status of logging data - success or fail
    default: success
  - name: enabled
    type: bool
    description: Enable or disable logging
    default: true


