environment:
  PYTEST_YAML_DEBUG: ${PYTEST_YAML_DEBUG}
  ROOT_DIR: ${ROOT_DIR}


schema:
- &DATA
  cls_name: Data
  slots: true
  description: Store data used by the functions in a module
  fields:
  - name: data
    description: Data passed to the decorator  # Come up with a better description
    type:  Any | None
    default: null
  - name: function
    description: A decorated function
    type: str | Callable | None
    default: null
  - name: module
    description: A function's parent module
    type: str | ModuleType | None
    default: null
  - name: args
    description: Arguments to pass to a function
    type: list | None
    default: null
  - name: timestamp
    description: Seconds since epoch
    type: int | None
    default: 0
  - name: kwargs
    description: Keyword arguments to pass to a function
    type: dict | None
    default: []
  - name: result
    description: The result of calling a function
    type: Any | None
    default: null
  - name: exception
    description: An exception that results from calling a function
    type: Exception | dict | None
    default: null
  - name: raise_exception
    description: Flag to raise an exception if one occurs
    type: bool | None
    default: null
  - name: default_value
    description: Default value to use if there is an exception
    type: Any | None
    default: null
  - name: log_enabled
    description: Flag to enable or disable logging
    type: bool | None
    default: null
  - name: log_level
    description: The level to log at
    type: str | None
    default: null
  - name: call_back
    description: Function that's called after the decorated function is executed
    type: Callable | dict | None
    default: null
  - name: standard_output
    description: Flag for printing to the terminal
    type: bool | None
    default: null

- &OPERATIONS
  cls_name: Operations
  description: Data for processing operations of functions in a module
  slots: False
  fields:
  - name: parameters
    type: dict | None
    description: A list of a functions parameters
    default: null
  - name: results
    type: dict | None
    description: The output from calling a function
    default: {}
  - name: fields
    type: dict | None
    description: Parameters and arguments to pass to a function
    default: {}
  - name: function
    type: Callable | None
    description: The current operation or function
    default: null


operations:
# - get_function_kind
# - get_event_loop
- handle_function_run
- process_output
# - log_output