environment:
  DEBUG: ${YAML_TESTING_FRAMEWORK_DEBUG}


empty_values:
- null
- None
- []
- {}
- ''
- False
- 'False'
- 'false'


operations:
- format_module_name
- get_module_from_pool
- get_module_from_location
- add_module_to_pool
