environment:
  ROOT_DIR: ${ROOT_DIR}
schema:
- &LOCATIONS
  cls_name: Locations
  slots: true
  description: Paths to a python and associated resources for testing
  fields:
  - name: project_directory
    type: str | None
    default: None
  - name: root_directory
    type: str | None
    default: None
    description: The location of project's root directory
  - name: modules
    type: str | list | None
    default: ''
  - name: yamls
    type: str | list | None
    default: ''
  - name: resources
    type: List[str] | str | None
    default: ''
  - name: exclude_files
    type: str | List[str] | None
    default: ''
  - name: yaml_suffix
    type: str | None
    default: _test
  - name: resources_folder_name
    type: str
    default: test_resources
  - name: include_functions
    type: str | List[str] | None
    default: ''
  - name: tmp
    type: Any | None
    default: null
  - name: module_routes
    type: list | None
    default: []
  # - name: yaml_locations
  #   type: list | None
  #   default: []
  # - name: resources_locations
  #   type: list | None
  #   default: []

# - &LOCATION
#   cls_name: Location
#   slots: true
#   description: Paths to a python and associated resources for testing
#   fields:
#   - name: module
#     type: str | None
#     default: ''
#   - name: yaml
#     type: str | None
#     default: ''
#   - name: resources
#     type: str | None
#     default: '' 


exclude_files:
- .venv
- .eggs
- build
- .ignore
- __pycache__
- .pyc
- .trunk


yaml_suffix: _test


exclude_functions: []


resources_folder_name: test_resources


location_extensions:
  module:
  - .py
  yaml:
  - .yaml
  - .yml
  resources:
  - .py


yaml_extensions:
- .yaml
- .yml


module_extension: .py


root_locations:
- .
- ./
- /
- //
- ''
- None
- null


empty_values:
- null
- None
- ''
- 0
- '0'
- False
- 'false'
- 'False'


operations:
- format_project_directory
- format_yaml_suffix
- format_resources_folder_name
- format_exclude_files
- format_resources
- get_yaml_locations
- get_module_locations
# - format_module_routes
- get_resources
