tests:
- functions: main
  description: Function description
  tests:
  - description: Test description
    arguments:
      data:
        a: 0
        b: 0
    cast_arguments:
      data: DataClass
    checks:
    - method: checks.app.check_equals
      expected: 0
    - method: checks.app.check_type
      expected: [int, float]
  - description: Test description
    arguments:
      a: 3
      b: 4
- functions: add_numbers
  description: Function description
  tests:
  - arguments:
      a: 1
      b: 2
    checks:
    - method: checks.app.check_equals
      expected: 3
    - method: checks.app.check_type
      expected: [int, float]
- functions: add_dataclass
  description: Function description
  tests:
  - arguments:
      data:
        a: 1
        b: 2
    checks:
    - method: checks.app.check_equals
      expected: 3
    - method: checks.app.check_type
      expected: [int, float]