environment:
  ROOT_DIR: ${YAML_TESTING_FRAMEWORK_ROOT_DIR}
  DEBUG: ${YAML_TESTING_FRAMEWORK_DEBUG}


exclude_files:
- .venv
- .eggs
- build
- .ignore
- __pycache__
- .pyc
- .trunk


yaml_suffix: _test


exclude_methods: []


yaml_extensions:
- .yaml
- .yml


module_extensions:
- .py


primary_secondary_map:
  module: yaml
  yaml: module


primary_secondary_types:
- module
- yaml


roots:
- .
- ./
- /
- //
- ''
- None
- null


empty_values:
- null
- None
- ''
- 0
- '0'
- False
- 'false'
- 'False'


operations:
  main:
  - format_path
  - format_yaml_suffix
  - format_inclusion_and_exclusion_patterns
  - get_paths
  handle_directory:
  - get_yaml_paths
  - get_module_paths
  - post_processing
