order_of_operations:
  location: &location
  - get_module_name
  - get_module_from_location
  pool:
  - get_module_from_pool # set data.module_name
  - *location
  - add_module_to_pool
  update:
  - *location
  - add_module_to_pool
  - get_module_from_pool


empty_values:
- null
- None
- []
- {}
- ''
- False
- 'False'
- 'false'


schema:
- &DATA
  cls_name: Data
  description: Data used by the functions within the module
  slots: false
  fields:
  - name: location
    description: Location of the module
    type: str | None
    default: null
  - name: name
    description: Name of the module
    type: str | None
    default: null
  - name: pool
    description: Flag to retrieve module from or save module to a pool
    type: bool
    default: true
  - name: module
    type: ModuleType | None
    description: Module retrieved from a location or the pool
    default: null


operations:
- format_module_name
- get_module_from_pool
- get_module_from_location
- add_module_to_pool
