environment:
  ROOT_DIR: ${YAML_TESTING_FRAMEWORK_ROOT_DIR}
  DEBUG: ${YAML_TESTING_FRAMEWORK_DEBUG}


empty_values:
- []
- {}
- null
- ''
- None
- '[]'
- '{}'


convert_fields_to_yaml:
- expected
- output


add_check_fields:
- output
- module
- id
- id_short


schema:
  Entry:
    description: Store data passed to `main` function of module
    fields:
    - &OUTPUT
      name: output
      type: Any
      description: Output from the function to verify
      default: null
    - &ID
      name: id
      description: >
        A unique ID for each test consisting of the route to the function, the
        tests unique key or number, and a description of the test
      type: str
      default: ''
    - &ID_SHORT
      name: id_short
      description: The route to the function
      type: str
      default: ''
    - &MODULE
      name: module
      type: ModuleType | str
      description: >
        The module containing the function to test or the module's location
      default: null
    - &CHECKS
      name: checks
      type: list
      default: null
      description: A list of checks to process to verify output from tests
  Check:
    description: Store data needed to process an check form a test
    fields:
    - *ID
    - *ID_SHORT
    - *MODULE
    - *OUTPUT
    - name: method
      type: str
      description: The check method
      default: null
    - name: field
      type: str
      description: Dot-delimited path to an attribute or key of the result
      default: null
    - name: expected
      type: Any
      default: null
      description: Expected value
    - name: cast_output
      type: list
      description: Casts to perform on the output before verifying expected output
      default: null
    - name: passed
      type: bool
      default: false
      description: Flag indicating whether a test was passed or not


operations:
  main:
  - get_check_method
  - reset_output_value
  - process_cast_output
  - get_check_result
  - handle_failed_check