environment:
  ROOT_DIR: ${ROOT_DIR}


schema:
- &ASSERTION
  cls_name: Assertion
  description: Store data needed to process an assertion form a test
  fields:
  - name: method
    type: str | None
    description: The assertion method
  - name: method_name
    type: str | None
    description: The name of an assertion method
  - name: field
    type: str | None
    description: Dot-delimited path to an attribute or key of the result
  - name: expected
    type: Any | None
    description: Expected value
  - name: output
    type: Any | None
    description: Output from the function to verify
  - name: exception
    type: dict | None
    description: Dictionary containing an exception
    default: null
  - name: cast_output
    type: list | None
    description: Casts to perform on the output before verifying expected output
  - name: passed
    type: bool | None
    default: false
    description: Flag indicating whether a test was passed or not
- &DATA
  cls_name: Data
  description: Store data used by the functions within the module
  fields:
  - name: module
    type: Any | None
    description: Module containing the verification or assertion functions
    default: null
  - name: assertions
    type: list | None
    description: List of dictionaries or assertion objects
    default: []
  - name: output
    type: Any | None
    description: Output from calling a function
    default: []
  - name: exception
    type: dict | None
    description: Exception from calling a function
    default: []
  - name: i
    type: int | None
    description: Value of the current iteration in a loop
    default: 0
  - name: assertion
    type: dict | None
    description: The ith assertion from a list of assertions
    default: {}


empty_values:
- []
- {}
- null
- ''
- None
- '[]'
- '{}'


operations:
- get_current_assertion
- get_assertion_method
- get_assertion_output_field
- get_casted_assertion_output
- verify_expected_output
- update_assertions_and_increment_i
